create table scope
(
    app_name   varchar(255),
    scope_name varchar(255),
    suffix     bigint,
    id         bigint GENERATED BY DEFAULT AS IDENTITY unique,
    primary key (app_name, scope_name, suffix)
);

create table users
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY unique,
    username varchar(255) not null,
    password varchar(20),
    email    varchar(255) not null,
    name     varchar(255) not null,
    primary key (username)
);

create table users_scope_association
(
    scope_id bigint,
    user_id  bigint,
    constraint user_fk foreign key (user_id) references users (id),
    constraint scope_fk foreign key (scope_id) references scope (id),
    primary key (user_id, scope_id)
);